### PR TITLE
fix display error in title of causalAssembly

### PR DESCRIPTION
**Pull request by windisch**
Fixes a display error of `causalAssembly` paper

image

### CODE REVIEW

**Review by lawrennd — CHANGES_REQUESTED** [review]
Thanks! Title itself should be markdown, so it won't support the texttt command. tex_title will do, but is only used for bib entries.

**Comment by windisch** [comment]
If I'm not mistaken, `$\texttt{something}$` should correctly rendered in markdown (it also works quite fine in the abstract). But you are right, it was still not correctly displayed. I now changed it to the code-environment - hope thats fine now!

Thanks!

**Comment by windisch** [comment]
Hi @lawrennd: Could you have an other look at my changes? Will it now be rendered correctly? Thanks a lot!

**Comment by lawrennd** [comment]
I think you haven't made the change in tex_title?

**Comment by windisch** [comment]
> I think you haven't made the change in tex_title?

@lawrennd: Ah, no I got it. Now `title` only holds markdown, `tex_title` holds tex code. Hope its fine now. Thanks!

**Review by lawrennd — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
